myproject/blog/urls.py
from django.urls import path
from .views import home_view, PostListView, PostDetailView

app_name = 'blog'
urlpatterns = [
    path('', home_view, name='home_view'),
    path('posts/', PostListView.as_view(), name='post_list_view'),
    path('posts/<int:id>/', PostDetailView.as_view(), name='post_detail_view'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls')),
]

myproject/blog/models.py
from django.db import models


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=120)
    body = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

myproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Post


def home_view(request, *args, **kwargs):
    return render(request, 'base.html', {})


class PostListView(ListView):
    template_name = 'post/list_view.html'
    queryset = Post.published.all().order_by('-title')

    model = Post
    context_object_name = 'pages'
    paginate_by = 2


class PostDetailView(DetailView):
    template_name = 'post/detail_view.html'

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Post, id=id_)

myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
    <title>
        {% block title %}
        Home
        {% endblock title %}
    </title>
</head>

<body>
<header>
    <div class="head">
        <div class="head__item">
            <div class="item1"><a href="{% url 'blog:post_list_view' %}">Blog</a></div>
            <div class="item2"><a href="{% url 'blog:home_view' %}">Home</a></div>

        </div>
    </div>
</header>

<div class="container">
    <div class="wrapper">

        <section>

            {% block content %}
            <div class="content">

                <div class="content__item1">
                    <div class="item1__img">
                        <img class="bird"
                             src="https://images.unsplash.com/photo-1587500020549-2144e7edcb1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80"
                             alt="White bird flying with blue sky and clouds behind">
                    </div>
                    <div class="item1__body">
                        <div class="item1__title">
                            <div>Some title</div>

                        </div>
                    </div>
                </div>

                <div class="content__item2">
                    <div class="item2__body">
                        <p><b>Lorem ipsum</b> dolor sit amet, consectetur adipisicing elit. <b>Veritatis</b> dolore
                            provident at
                            ut
                            consectetur quos explicabo quo vitae consequatur, eos quisquam est saepe?</p>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas deleniti, dolores sequi
                            minus
                            optio ad omnis, ipsam maiores aut odit atque consectetur vel praesentium velit.</p>
                    </div>
                </div>
            </div>
            <div class="content2">
                <div class="content2__title">
                    <div>Lorem, ipsum.</div>
                </div>
                <div class="content2__body">
                    <div class="text">
                        <b>Lorem ipsum</b> dolor sit amet consectetur, adipisicing elit. Modi explicabo dolorum
                        voluptatibus
                        magnam, laudantium voluptatem culpa, error ipsam in asperiores, dolorem rerum suscipit ab?
                        Laboriosam accusamus, voluptatem explicabo maiores nulla, temporibus iste non ullam in aliquam
                        odio
                        vel commodi libero provident, minus aut corrupti cum beatae amet. Laboriosam, quos blanditiis.
                    </div>
                    <div class="text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. <b> Fugiat temporibus
                        harum,
                        minus porro</b>
                        exercitationem pariatur rem quasi dolorum, id ab laborum corporis nobis praesentium voluptatibus
                        quia optio assumenda odit eos minima quis vitae velit. Cumque vel id molestiae consequatur nisi
                        necessitatibus blanditiis mollitia, neque itaque rerum, consectetur cum voluptatibus, deserunt
                        ea
                        quam ipsa quibusdam.
                        Repellendus <b> dolores est deleniti suscipit doloribus quia beatae, ex corrupti
                            ab velit ducimus facilis error. Quia quaerat illo quisquam architecto voluptatem </b>similique
                        nisi
                        ullam totam alias ut porro necessitatibus tempore iure suscipit illum fugiat quibusdam, ipsa
                        assumenda, impedit distinctio quae beatae velit deleniti fuga? Quam ratione minima, quo quasi
                        consequatur facere sint odio. Voluptate, blanditiis eos sint dolores, a dolorem, eaque
                        voluptates
                        delectus ad velit dignissimos?
                    </div>
                </div>
            </div>
            {% endblock content %}

        </section>
    </div>
</div>
{% include 'include/footer.html' %}


</body>

</html>

myproject/templates/include/footer.html
<footer class="footer">
    <div class="footer__body">
        <span class="year">&#8987; 2020, April </span>
    </div>
</footer>

myproject/templates/include/pagination.html
<div class="my_pagination">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a class="page-link" href="?page=1">&laquo; FIRST</a></li>
        <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">PREVIOUS</a></li>
        {% endif %}


        {% if page_obj.has_next %}
        <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">NEXT</a></li>
        <li><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">LAST &raquo;</a></li>
        {% endif %}
    </ul>
    <span class="nav justify-content-center" style="color: gray;"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
</div>

myproject/templates/post/detail_view.html
{% extends 'base.html' %}

{% block title %}

{{ post.title }}

{% endblock title %}

{% block content %}
<div class="content2__title blog__title">
    {{ post.title|safe}}
</div>
<div class="text blog__text">
    {{ post.body|safe}}
</div>
{% endblock content %}

myproject/templates/post/list_view.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock title %}

{% block content %}

{% for post in object_list %}
<div class="content2__title blog__title">
    <a href="{{ post.id }}">{{ post.title|safe }}</a>
</div>
<div class="text__blur">
    <ul>
        <ol>
            <div class="text">
                {{ post.body|safe|truncatewords:90 }}
            </div>
        </ol>
    </ul>

</div>
{% endfor %}


{% include 'include/pagination.html' %}

{% endblock content %}